-- Titres FR / ES pour les 634 recettes Wikibooks publiées qui n’avaient qu’un titre anglais.
-- Appliquée en production le 2026-10-05 (version Supabase 20261005165301).
-- Correspondance par rang (ordre des id) parmi les recettes publiées sans titre FR, avec garde-fou :
-- l’ajout n’a lieu que si le nombre et les titres témoins correspondent exactement à l’instantané de production.
-- Sur une base créée à partir du dépôt (les 634 recettes n’y sont pas), la migration ne fait rien
-- au lieu d’échouer, pour ne pas bloquer un « supabase db reset ».
-- Retour arrière : delete from public.recipe_title_translations where model = 'claude-titres-2026-10-05';
do $migration$
declare n_total int; t1 text; t320 text; t634 text;
begin
  select count(*) into n_total from public.recipes r where r.status='published'
    and not exists (select 1 from public.recipe_title_translations x where x.recipe_id=r.id and x.language_code='fr');
  if n_total = 0 then return; end if;
  select title into t1 from (select title, row_number() over (order by r.id) n from public.recipes r where r.status='published'
    and not exists (select 1 from public.recipe_title_translations x where x.recipe_id=r.id and x.language_code='fr')) s where n=1;
  select title into t320 from (select title, row_number() over (order by r.id) n from public.recipes r where r.status='published'
    and not exists (select 1 from public.recipe_title_translations x where x.recipe_id=r.id and x.language_code='fr')) s where n=320;
  select title into t634 from (select title, row_number() over (order by r.id) n from public.recipes r where r.status='published'
    and not exists (select 1 from public.recipe_title_translations x where x.recipe_id=r.id and x.language_code='fr')) s where n=634;
  if n_total <> 634 or t1 is distinct from 'Palaver Sauce' or t320 is distinct from 'Wakeup Sausage Casserole'
     or t634 is distinct from 'Liberian Chicken Gravy' then
    -- Ensemble différent de la production : on n’ajoute rien (aucune erreur).
    raise notice 'Titres Wikibooks ignorés : ensemble inattendu (%, %, %, %)', n_total, t1, t320, t634;
    return;
  end if;

with t(n, fr, es) as (values
(1,'Sauce palaver','Salsa palaver'),(2,'Pain taboon','Pan taboon'),(3,'Biscuits croquants au gingembre','Galletas crujientes de jengibre'),(4,'Pâte brisée','Masa quebrada'),(5,'Ekuru (pouding de haricots blancs)','Ekuru (pudin de alubias blancas)'),(6,'Œuf roulé nigérian','Rollo de huevo nigeriano'),(7,'Pâté jamaïcain','Empanada jamaicana'),(8,'Biscuits et sauce gravy','Biscuits con salsa gravy'),(9,'Arancini (boulettes de riz frites italiennes)','Arancini (bolas de arroz fritas italianas)'),(10,'Riz « concoction » nigérian','Arroz «concoction» nigeriano'),
(11,'Sablés écossais (shortbread)','Galletas escocesas de mantequilla (shortbread)'),(12,'Muffins aux bananes et pépites de chocolat','Magdalenas de plátano con chispas de chocolate'),(13,'Lait frappé à la banane','Batido de plátano'),(14,'Sauce veloutée','Salsa velouté'),(15,'Beurre au brandy','Mantequilla al brandy'),(16,'Biryani au poulet','Biryani de pollo'),(17,'Paella valencienne','Paella valenciana'),(18,'Calzone','Calzone'),(19,'Lait d’amande II','Leche de almendras II'),(20,'Ciabatta','Chapata'),
(21,'Une bonne tasse de thé','Una buena taza de té'),(22,'Tarte au citron meringuée (américaine)','Tarta de limón y merengue (estadounidense)'),(23,'Brigadeiro (bouchée brésilienne au chocolat)','Brigadeiro (dulce brasileño de chocolate)'),(24,'Riz et pois à la jamaïcaine','Arroz con frijoles a la jamaicana'),(25,'Vinaigrette à l’ail et à la moutarde','Vinagreta de ajo y mostaza'),(26,'Gâteau fondant « atomique »','Pastel de chocolate «atómico»'),(27,'Knödel en serviette autrichien (Serviettenknödel)','Knödel austriaco en servilleta (Serviettenknödel)'),(28,'Foufou de taro','Fufú de malanga'),(29,'Croustilles barbecue','Papas chips sabor barbacoa'),(30,'Tartiflette','Tartiflette'),
(31,'Chou cavalier braisé','Berza braseada'),(32,'Brochettes de fruits nigérianes','Brochetas de fruta nigerianas'),(33,'Dessert banane-caramel','Postre de plátano y caramelo'),(34,'Polenta','Polenta'),(35,'Bouts de côtes de bœuf braisés','Costillas cortas de res estofadas'),(36,'Frikadeller (boulettes de viande danoises)','Frikadeller (albóndigas danesas)'),(37,'Biscuits aux pépites de chocolat II','Galletas con chispas de chocolate II'),(38,'Achar de citron I','Encurtido de limón I'),(39,'Œufs au thé','Huevos al té'),(40,'Gâteau aux biscuits','Pastel de galletas'),
(41,'Rôtie au lait II','Tostada con leche II'),(42,'Pain aux bananes et aux noix de Grenoble','Pan de plátano con nueces'),(43,'Boliche (rôti cubain farci au chorizo)','Boliche (asado cubano relleno de chorizo)'),(44,'Éclairs','Éclairs'),(45,'Patate douce bouillie','Batata hervida'),(46,'Poitrines de canard grillées à l’asiatique','Pechugas de pato a la parrilla al estilo asiático'),(47,'Croque-monsieur','Croque-monsieur'),(48,'Gyros au poulet','Gyros de pollo'),(49,'Gâteau aux amandes','Pastel de almendras'),(50,'Riz à la noix de coco (indien)','Arroz con coco (indio)'),
(51,'Pigeon grillé égyptien (fattah meshaltet)','Pichón a la parrilla egipcio (fattah meshaltet)'),(52,'Pâtes carbonara','Pasta carbonara'),(53,'Ragoût égyptien de gombo','Guiso egipcio de quimbombó'),(54,'Sauce bolognaise','Salsa boloñesa'),(55,'Omelette aux pois chiches','Tortilla de garbanzos'),(56,'Enchilada au fromage','Enchilada de queso'),(57,'Salade africaine I','Ensalada africana I'),(58,'Champignons farcis aux légumes','Champiñones rellenos de verduras'),(59,'Pommes de terre rissolées (hash browns)','Papas ralladas doradas (hash browns)'),(60,'Pouding au pain, banane et chocolat','Budín de pan con plátano y chocolate'),
(61,'Crème à la banane I','Crema de plátano I'),(62,'Salade de chou','Ensalada de col'),(63,'Osso buco à la milanaise','Osobuco a la milanesa'),(64,'Ragoût de pois chiches','Guiso de garbanzos'),(65,'Carpaccio de bœuf I','Carpaccio de res I'),(66,'Fudge au chocolat','Dulce de chocolate (fudge)'),(67,'Poulet du couronnement (coronation chicken)','Pollo de la coronación (coronation chicken)'),(68,'Baklava','Baklava'),(69,'Ragoût africain au chou','Guiso africano de col'),(70,'Croustilles','Papas chips'),
(71,'Viande à tacos','Carne para tacos'),(72,'Tomates farcies au fromage','Tomates rellenos de queso'),(73,'Crème de champignons','Crema de champiñones'),(74,'Poulet BBQ fumé au hickory','Pollo BBQ ahumado con hickory'),(75,'Pouding aux pommes à l’américaine (cobbler)','Cobbler de manzana'),(76,'Paksiw na bangus (poisson-lait mijoté au vinaigre)','Paksiw na bangus (pez lechero estofado en vinagre)'),(77,'Cirdingis (viande et boulettes tchétchènes)','Cirdingis (carne y bolas de masa chechenas)'),(78,'Chili colorado','Chile colorado'),(79,'Soupe d’agneau et légumes de Liverpool (scouse)','Sopa de cordero y verduras de Liverpool (scouse)'),(80,'Gâteau 1-2-3-4','Pastel 1-2-3-4'),
(81,'Poulet au cari californien','Pollo al curry californiano'),(82,'Pouding aux pommes','Budín de manzana'),(83,'Chou à la crème','Profiterol de crema'),(84,'Burrito déjeuner','Burrito de desayuno'),(85,'Cari de crevettes','Curry de camarones'),(86,'Biscuit de mer (hardtack)','Galleta marinera (hardtack)'),(87,'Sauce caramel II','Salsa de caramelo II'),(88,'Sucettes glacées aux fruits','Paletas heladas de fruta'),(89,'Crêpes au fromage cottage','Panqueques de requesón'),(90,'Cari de poulet','Curry de pollo'),
(91,'Amandes caramélisées (brända mandlar)','Almendras garrapiñadas (brända mandlar)'),(92,'Asida bil zibda (pouding libyen à la semoule)','Asida bil zibda (pudin libio de sémola)'),(93,'Omelette au fromage','Tortilla de queso'),(94,'Pois chiches épicés','Garbanzos picantes'),(95,'Paella aux fruits de mer','Paella de marisco'),(96,'Chachlik (brochettes russes)','Shashlik (brochetas rusas)'),(97,'Sauce crémeuse au citron','Salsa cremosa de limón'),(98,'Fèves au lard de Boston','Frijoles horneados de Boston'),(99,'Gumbo aux fruits de mer','Gumbo de mariscos'),(100,'Salade « œil de grenouille » (frog’s eye salad)','Ensalada «ojo de rana» (frog’s eye salad)'),
(101,'Tapioca aux pommes','Tapioca con manzana'),(102,'Jambalaya II','Jambalaya II'),(103,'Farce aux pommes','Relleno de manzana'),(104,'Poudre de chili II','Chile en polvo II'),(105,'Riz au citron','Arroz al limón'),(106,'Maïs aux fines herbes','Maíz a las hierbas'),(107,'Huile pimentée','Aceite de chile'),(108,'Lait de sésame','Leche de sésamo'),(109,'Paella rouge','Paella roja'),(110,'Soupe aux lentilles','Sopa de lentejas'),
(111,'Tarte au citron meringuée (britannique)','Tarta de limón y merengue (británica)'),(112,'Buckeyes (bouchées beurre d’arachide et chocolat)','Buckeyes (bocados de mantequilla de maní y chocolate)'),(113,'Lait frappé au lait de poule (végane)','Batido de ponche de huevo (vegano)'),(114,'Soupe otong','Sopa otong'),(115,'Macarons au chocolat (sans cuisson)','Macarrones de chocolate (sin horno)'),(116,'Spritzgebäck (biscuits au beurre allemands)','Spritzgebäck (galletas alemanas de mantequilla)'),(117,'Muffins double chocolat','Magdalenas de doble chocolate'),(118,'Caldo gambien (soupe aux fruits de mer)','Caldo gambiano (sopa de mariscos)'),(119,'Trempette épinards et artichauts','Dip de espinacas y alcachofas'),(120,'Boulettes de viande égyptiennes (kofta)','Albóndigas egipcias (kofta)'),
(121,'Soupe afang','Sopa afang'),(122,'Glaçage balsamique','Reducción de balsámico'),(123,'Gajar halwa (pouding aux carottes)','Gajar halwa (pudin de zanahoria)'),(124,'Cigares au chou en sauce au yogourt (sarmi)','Rollos de col en salsa de yogur (sarmi)'),(125,'Biscuits à la noix de coco','Galletas de coco'),(126,'Beignets polonais (pączki)','Berlinas polacas (pączki)'),(127,'Smoothie amande-cowitch au matcha','Batido de almendra, cowitch y matcha'),(128,'Boules de pommes de terre','Bolitas de papa'),(129,'Haupia (pouding hawaïen à la noix de coco)','Haupia (pudin hawaiano de coco)'),(130,'Cigares au chou égyptiens (mahshi malfoof)','Rollos de col egipcios (mahshi malfoof)'),
(131,'Sandwich aux frites (chip butty)','Sándwich de papas fritas (chip butty)'),(132,'Salade israélienne','Ensalada israelí'),(133,'Pâtés au bœuf','Empanadas de res'),(134,'Jollof de macaronis nigérian','Jollof de macarrones nigeriano'),(135,'Beurre aux œufs','Mantequilla de huevo'),(136,'Limonade','Limonada'),(137,'Soupe aux tomates épicée','Sopa de tomate picante'),(138,'Burger au seitan','Hamburguesa de seitán'),(139,'Salade de légumes','Ensalada de verduras'),(140,'Tempe mendoan II','Tempe mendoan II'),
(141,'Chutney à la noix de coco (Inde du Sud)','Chutney de coco (sur de la India)'),(142,'Soupe aux légumes','Sopa de verduras'),(143,'Foie et oignons','Hígado encebollado'),(144,'Ketchup au chipotle','Kétchup de chipotle'),(145,'Pomme à la moutarde et au fromage de chèvre','Manzana con mostaza y queso de cabra'),(146,'Riz aux œufs','Arroz con huevo'),(147,'Baba ganoush','Baba ganoush'),(148,'Calmars croustillants','Calamares crujientes'),(149,'Hamburger','Hamburguesa'),(150,'Rouleau impérial aux légumes','Rollito de primavera de verduras'),
(151,'Orange Julius','Orange Julius'),(152,'Bœuf séché (jerky)','Cecina de res (jerky)'),(153,'Gnocchis aux épinards et à la ricotta','Ñoquis de espinaca y ricota'),(154,'Brownies à la cassonade','Brownies de azúcar moreno'),(155,'Galettes de pommes de terre écossaises (tattie scones)','Tortitas escocesas de papa (tattie scones)'),(156,'Ají de gallina (poulet péruvien au piment)','Ají de gallina (pollo peruano al ají)'),(157,'Gâteau aux bananes','Pastel de plátano'),(158,'Pouding au lait égyptien (mahalabiya)','Pudin de leche egipcio (mahalabiya)'),(159,'Thon grillé à la méditerranéenne','Atún a la parrilla mediterráneo'),(160,'Gâteau aux pommes et aux amandes','Pastel de manzana y almendras'),
(161,'Burgers de bœuf aux oignons','Hamburguesas de res con cebolla'),(162,'Arroz con pollo (riz au poulet)','Arroz con pollo'),(163,'Tagliatelles gratinées','Tallarines gratinados'),(164,'Meringue italienne','Merengue italiano'),(165,'Pâté du berger I (shepherd’s pie)','Pastel del pastor I (shepherd’s pie)'),(166,'Salade de poulet au sésame','Ensalada de pollo con sésamo'),(167,'Gâteau au chocolat 1-2','Pastel de chocolate 1-2'),(168,'Behari kebab','Behari kebab'),(169,'Börek (feuilletés turcs farcis)','Börek (hojaldres turcos rellenos)'),(170,'Igname frite et sauce aux piments','Ñame frito con salsa de pimiento'),
(171,'Cari de bananes','Curry de plátano'),(172,'Biscuits aux pépites de chocolat I','Galletas con chispas de chocolate I'),(173,'Gâteau aux pommes','Pastel de manzana'),(174,'Poitrines de poulet au four','Pechugas de pollo al horno'),(175,'Pâté végane','Paté vegano'),(176,'Gyudon (bol de riz au bœuf japonais)','Gyudon (cuenco japonés de arroz con res)'),(177,'Bouchée à la reine','Volován a la reina'),(178,'Bœuf séché à la crème sur rôtie','Cecina en salsa cremosa sobre tostada'),(179,'Burger bœuf et champignons','Hamburguesa de res y champiñones'),(180,'Croustade aux fruits (crumble)','Crumble de frutas'),
(181,'Crêpes jambon-fromage','Crepas de jamón y queso'),(182,'Pâte à frire à la bière','Rebozado de cerveza'),(183,'Habichuela con dulce (crème de haricots sucrée dominicaine)','Habichuelas con dulce dominicanas'),(184,'Couronne d’agneau rôtie','Corona de cordero asada'),(185,'Sandwich au jus','Sándwich au jus'),(186,'Fajitas au bœuf','Fajitas de res'),(187,'Riz à la noix de coco aux légumes','Arroz con coco y verduras'),(188,'Poisson au taro','Pescado con taro'),(189,'Gambas al ajillo (crevettes à l’ail)','Gambas al ajillo'),(190,'Linguine au pesto d’épinards','Linguine con pesto de espinacas'),
(191,'Rondelles d’oignon','Aros de cebolla'),(192,'Limoncello','Limoncello'),(193,'Hallaca (pâte de maïs farcie vénézuélienne)','Hallaca venezolana'),(194,'Goulache de Szeged','Gulash de Szeged'),(195,'Harissa bil djaj (poulet libyen à la harissa)','Harissa bil djaj (pollo libio con harissa)'),(196,'Burgers aux lentilles','Hamburguesas de lentejas'),(197,'Chin chin nigérian','Chin chin nigeriano'),(198,'Omelette bacon et fromage','Tortilla de tocino y queso'),(199,'Smoothie avocat et noix de coco','Batido de aguacate y coco'),(200,'Soupe à l’oignon','Sopa de cebolla'),
(201,'Pouding de Noël britannique','Pudin de Navidad británico'),(202,'Sauce au fromage I','Salsa de queso I'),(203,'Pot-au-feu','Pot-au-feu (cocido francés)'),(204,'OpenCola','OpenCola'),(205,'Casserole de pommes de terre rissolées','Cazuela de papas ralladas'),(206,'Poulet frit à la campagnarde','Pollo frito al estilo campestre'),(207,'Carrés au citron','Cuadritos de limón'),(208,'Pommes de terre rôties croustillantes','Papas asadas crujientes'),(209,'Frito pie (au four)','Frito pie (al horno)'),(210,'Poulet frit croustillant cantonais','Pollo frito crujiente cantonés'),
(211,'Riz doré','Arroz dorado'),(212,'Sauce barbecue I','Salsa barbacoa I'),(213,'Pain aux bananes et pacanes','Pan de plátano y nueces pecanas'),(214,'Jus de baobab gambien (bouye)','Jugo de baobab gambiano (bouye)'),(215,'Assaisonnement pour fruits de mer','Sazonador para mariscos'),(216,'Crème anglaise nigériane (custard)','Natillas nigerianas'),(217,'Awaze tibs (sauté de viande épicé éthiopien)','Awaze tibs (salteado etíope de carne picante)'),(218,'Bicol express','Bicol express'),(219,'Pain au levain naturel','Pan de masa madre'),(220,'Bison à la grecque','Bisonte a la griega'),
(221,'Patates douces confites','Batatas confitadas'),(222,'Croquants à la vanille','Crujientes de vainilla'),(223,'Bhuna khichuri (riz et lentilles bengalis)','Bhuna khichuri (arroz y lentejas bengalíes)'),(224,'Biscuits américains II','Biscuits estadounidenses II'),(225,'Couscous algérien','Cuscús argelino'),(226,'Gâteau au chocolat de la Saint-Valentin','Pastel de chocolate de San Valentín'),(227,'Salade tarbaise','Ensalada de Tarbes'),(228,'Alkubus (pain vapeur nigérian)','Alkubus (pan al vapor nigeriano)'),(229,'Chili pour frito pie','Chili para frito pie'),(230,'Croustade aux pommes III','Crujiente de manzana III'),
(231,'Gâteau éponge I','Bizcocho I'),(232,'Ragoût d’œufs nigérian','Guiso de huevo nigeriano'),(233,'Porc et carottes en sauce','Cerdo con zanahorias en salsa'),(234,'Mayonnaise au citron','Mayonesa de limón'),(235,'Rôtie au fromage et à l’œuf','Tostada de queso y huevo'),(236,'Menudo (soupe mexicaine aux tripes et au maïs lessivé)','Menudo (sopa mexicana de pancita y maíz pozolero)'),(237,'Soupe mexicaine aux tomates','Sopa mexicana de tomate'),(238,'Riz à la noix de coco (nasi lemak)','Arroz con coco (nasi lemak)'),(239,'Tarte aux Oreo','Tarta de Oreo'),(240,'Ragoût de poisson frit nigérian','Guiso nigeriano de pescado frito'),
(241,'Soupe égyptienne aux lentilles','Sopa egipcia de lentejas'),(242,'Poulet BBQ de cour arrière','Pollo a la barbacoa de patio'),(243,'Tapenade','Tapenade'),(244,'Lait de poule','Ponche de huevo'),(245,'Pain frit II (fry bread)','Pan frito II (fry bread)'),(246,'Jalebi (beignets au sirop)','Jalebi (buñuelos en almíbar)'),(247,'Mélange d’épices à frotter pour poulet','Adobo seco para pollo'),(248,'Meringues I','Merenguitos I'),(249,'Asun (chèvre en sauce piquante)','Asun (cabra en salsa picante)'),(250,'Binagoongan (porc sauté à la pâte de crevettes)','Binagoongan (cerdo salteado con pasta de camarón)'),
(251,'Halo-halo (dessert philippin étagé)','Halo-halo (postre filipino en capas)'),(252,'Fromage fondu sur rôtie','Queso fundido sobre tostada'),(253,'Assaisonnement à l’italienne','Sazonador italiano'),(254,'Beignets d’épinards','Buñuelos de espinaca'),(255,'Stargazy pie (tourte aux sardines)','Stargazy pie (pastel de sardinas)'),(256,'Thé à la menthe algérien','Té de menta argelino'),(257,'Brochettes de foie','Brochetas de hígado'),(258,'Poulet barbecue','Pollo a la barbacoa'),(259,'Gelée de pommes','Jalea de manzana'),(260,'Riz frit aux fruits de mer','Arroz frito con mariscos'),
(261,'Croustade aux pommes II','Crujiente de manzana II'),(262,'Crêpes au citron et aux bleuets','Panqueques de limón y arándanos'),(263,'Ragoût de bœuf I','Estofado de res I'),(264,'Salade chopska (tomates, concombre et poivron)','Ensalada shopska (tomate, pepino y pimiento)'),(265,'Pan de jamón (pain au jambon vénézuélien)','Pan de jamón'),(266,'Com chien (riz frit vietnamien)','Com chien (arroz frito vietnamita)'),(267,'Knödel au fromage (Kaspressknödel)','Albóndigas de queso (Kaspressknödel)'),(268,'Tzatziki','Tzatziki'),(269,'Poulet grillé nigérian','Pollo a la parrilla nigeriano'),(270,'Shikanjvi (limonade épicée du Pendjab)','Shikanjvi (limonada especiada del Punyab)'),
(271,'Salade d’algues','Ensalada de algas'),(272,'Banane farcie au feu de camp','Plátano relleno a la fogata'),(273,'Pizza aux fruits de mer','Pizza de mariscos'),(274,'Sauce à tacos','Salsa para tacos'),(275,'Nouilles sautées de Shanghai','Fideos salteados de Shanghái'),(276,'Vinaigrette balsamique','Aderezo balsámico'),(277,'Vanillekipferl (croissants aux amandes)','Vanillekipferl (medialunas de almendra)'),(278,'Tartelette au mincemeat à la viande I','Pastelito de mincemeat con carne I'),(279,'Gâteau à la compote de pommes','Pastel de puré de manzana'),(280,'Ailes de poulet frites épicées','Alitas fritas picantes'),
(281,'Côtelettes de porc au four','Chuletas de cerdo al horno'),(282,'Fond de bœuf','Caldo de res'),(283,'Pains bao vapeur au thon','Bollos bao al vapor con atún'),(284,'Vinaigrette italienne I','Aderezo italiano I'),(285,'Coddle (ragoût dublinois)','Coddle (guiso dublinés)'),(286,'Thé aux perles (bubble tea)','Té de burbujas'),(287,'Salade de fruits ambroisie','Ensalada de frutas ambrosía'),(288,'Gâteau au fromage au chocolat','Tarta de queso de chocolate'),(289,'Épinards à la crème','Espinacas a la crema'),(290,'Nouilles nigérianes','Fideos nigerianos'),
(291,'Glaçage au fudge','Glaseado de fudge'),(292,'Pouding à la semoule','Pudin de sémola'),(293,'Pouding aux bananes','Pudin de plátano'),(294,'Gruau nigérian','Avena nigeriana'),(295,'Ropa vieja panaméenne','Ropa vieja panameña'),(296,'Cari de bœuf','Curry de res'),(297,'Rôtie au lait I','Tostada con leche I'),(298,'Tarte aux pommes I','Tarta de manzana I'),(299,'Gözleme (galette turque)','Gözleme (pan plano turco)'),(300,'Dodo nigérian (banane plantain mûre frite)','Dodo nigeriano (plátano maduro frito)'),
(301,'Churros II','Churros II'),(302,'Fudge à la vanille I','Dulce de vainilla (fudge) I'),(303,'Crêpes au citron et aux graines de pavot','Panqueques de limón y semillas de amapola'),(304,'Fajitas au poulet','Fajitas de pollo'),(305,'Tourte au bacon et aux œufs','Pastel de tocino y huevo'),(306,'Ceviche des îles','Ceviche isleño'),(307,'Appam (crêpe de riz fermentée)','Appam (crepa de arroz fermentado)'),(308,'Crème glacée à la vanille (base anglaise)','Helado de vainilla (base de natillas)'),(309,'Ignames confites (candied yams)','Ñames confitados (candied yams)'),(310,'Soupe aux asperges','Sopa de espárragos'),
(311,'Tandoori masala','Tandoori masala'),(312,'Camotes enmielados (patates douces au miel mexicaines)','Camotes enmielados'),(313,'Riz mexicain I','Arroz mexicano I'),(314,'Biscuits craquelés au chocolat','Galletas craqueladas de chocolate'),(315,'Salade classique','Ensalada clásica'),(316,'Lait d’amande I','Leche de almendras I'),(317,'Rôti de bœuf braisé classique','Asado de res a la olla clásico'),(318,'Ziti au four','Ziti al horno'),(319,'Poulet aux graines de pavot','Pollo con semillas de amapola'),(320,'Casserole déjeuner aux saucisses','Cazuela de salchicha para el desayuno'),
(321,'Poulet rôti à la campagnarde','Pollo asado campestre'),(322,'Agneau rôti égyptien (kharouf mahshi)','Cordero asado egipcio (kharouf mahshi)'),(323,'Boulghour du jardin','Bulgur de la huerta'),(324,'Biscuits Anzac I','Galletas Anzac I'),(325,'Pâté au poisson nigérian','Empanada de pescado nigeriana'),(326,'Pain frit I (fry bread)','Pan frito I (fry bread)'),(327,'Biscuits aux pépites de chocolat (véganes)','Galletas con chispas de chocolate (veganas)'),(328,'Fromage en saumure poêlé (saganaki)','Queso en salmuera a la sartén (saganaki)'),(329,'Pommes de terre rôties au four','Papas asadas al horno'),(330,'Pohe (riz aplati épicé)','Pohe (arroz aplanado especiado)'),
(331,'Biryani','Biryani'),(332,'Ukpo oka (pouding de maïs nigérian)','Ukpo oka (pudin de maíz nigeriano)'),(333,'Œufs rôtis à la keralaise (egg roast)','Huevos asados al estilo de Kerala (egg roast)'),(334,'Saumon en croûte de glands','Salmón con costra de bellotas'),(335,'Plantain vert frit nigérian','Plátano verde frito nigeriano'),(336,'Mélange à chili','Mezcla para chili'),(337,'Torte aux noisettes','Torta de avellanas'),(338,'Gâteau au fromage crème brûlée','Tarta de queso crème brûlée'),(339,'Salade César','Ensalada César'),(340,'Riz banga','Arroz banga'),
(341,'Smoothie fruité du jour','Batido de frutas del día'),(342,'Ragoût de pommes de terre','Guiso de papas'),(343,'Croustade aux pommes I','Crujiente de manzana I'),(344,'Bagel grillé','Bagel tostado'),(345,'Gelée d’agar-agar','Gelatina de agar'),(346,'Achar de citron II','Encurtido de limón II'),(347,'Soupe à la laitue','Sopa de lechuga'),(348,'Colcannon','Colcannon'),(349,'Crêpes I','Crepas I'),(350,'Sauce barbecue (sucrée)','Salsa barbacoa (dulce)'),
(351,'Sauce au beurre à l’ail','Salsa de mantequilla y ajo'),(352,'Tempura','Tempura'),(353,'Igname frite nigériane','Ñame frito nigeriano'),(354,'Œufs Connaught','Huevos Connaught'),(355,'Adalu (bouillie de haricots et maïs)','Adalu (gachas de frijoles y maíz)'),(356,'Pouding au steak et aux rognons','Pudin de carne y riñones'),(357,'Cioppino (ragoût de fruits de mer à l’italienne)','Cioppino (guiso italiano de mariscos)'),(358,'Haricots rouges et riz cajun','Frijoles rojos con arroz cajún'),(359,'Tourte au steak et à la bière','Pastel de carne y cerveza ale'),(360,'Salade taco','Ensalada de tacos'),
(361,'Pouding au pain','Budín de pan'),(362,'Ragoût de légumes et grands-pères','Guiso de verduras con bolitas de masa'),(363,'Salade caprese','Ensalada caprese'),(364,'Trempette épicée au cheddar et aux olives','Dip picante de cheddar y aceitunas'),(365,'Canard rôti cantonais','Pato asado cantonés'),(366,'Ananas caramélisé','Piña caramelizada'),(367,'Riz basmati au micro-ondes','Arroz basmati al microondas'),(368,'Bratwurst de seitan','Bratwurst de seitán'),(369,'Pommes de terre farcies cuites deux fois I','Papas rellenas horneadas dos veces I'),(370,'Pain doré à l’orange','Torrijas de naranja'),
(371,'Riz mexicain II','Arroz mexicano II'),(372,'Poulet épicé au piment','Pollo picante al chile'),(373,'Soupe aux ailerons de requin','Sopa de aleta de tiburón'),(374,'Nouilles aux œufs II','Fideos de huevo II'),(375,'Tarte au fromage','Tarta de queso'),(376,'Barfi à la noix de coco','Barfi de coco'),(377,'Boules au chocolat','Bolitas de chocolate'),(378,'Soupe ager','Sopa ager'),(379,'Soupe ora I','Sopa ora I'),(380,'Pâté impérial (egg roll)','Rollo de huevo frito (egg roll)'),
(381,'Poisson frit nigérian','Pescado frito nigeriano'),(382,'Chili au chipotle','Chili con chipotle'),(383,'Pakoras aux épinards','Pakoras de espinaca'),(384,'Gâteau éponge II','Bizcocho II'),(385,'Bonda (beignet de légumes de l’Inde du Sud)','Bonda (buñuelo de verduras del sur de la India)'),(386,'Sauce pad thaï','Salsa para pad thai'),(387,'Soupe nigériane au gombo I','Sopa nigeriana de quimbombó I'),(388,'Carrés au caramel','Cuadritos de caramelo'),(389,'Poulet croustillant','Pollo crujiente'),(390,'Foul medames (fèves égyptiennes)','Ful medames (habas egipcias)'),
(391,'Bouts de côtes braisés','Costillas cortas braseadas'),(392,'Bouillabaisse','Bullabesa'),(393,'Œufs aux jalapeños','Huevos con jalapeños'),(394,'Salade de fruits au soda à l’orange (ensalada de fruta)','Ensalada de fruta con refresco de naranja'),(395,'Gruau cuit au four','Avena horneada'),(396,'Bortsch ukrainien','Borsch ucraniano'),(397,'Foufou aux épinards','Fufú de espinaca'),(398,'Pizza poulet Alfredo','Pizza de pollo Alfredo'),(399,'Salade végé','Ensalada vegetal'),(400,'Chilaquiles','Chilaquiles'),
(401,'Soupe banga','Sopa banga'),(402,'Soupe atama','Sopa atama'),(403,'Pouding de Noël II','Pudin de Navidad II'),(404,'Fourmis sur une bûche (céleri, beurre d’arachide et raisins secs)','Hormigas en un tronco (apio, mantequilla de maní y pasas)'),(405,'Salade de nouilles au sésame','Ensalada de fideos con sésamo'),(406,'Casserole déjeuner','Cazuela de desayuno'),(407,'Huile à l’ail épicée','Aceite picante de ajo'),(408,'Barres aux pommes','Barritas de manzana'),(409,'Pouding éponge au citron','Bizcocho de limón'),(410,'Chili texan original','Chili original estilo Texas'),
(411,'Bouillie de plantain vert','Gachas de plátano verde'),(412,'Pâté à la viande nigérian','Empanada de carne nigeriana'),(413,'Frites de patates douces croustillantes','Papas fritas de batata crujientes'),(414,'Boisson au jus de calamansi','Bebida de jugo de calamansi'),(415,'Tourte aux aubergines et oignons','Pastel de berenjena y cebolla'),(416,'Mincemeat (garniture aux fruits secs)','Mincemeat (relleno de frutas secas)'),(417,'Poireaux au four','Puerros al horno'),(418,'Croustillants au fromage','Crujientes de queso'),(419,'Cari de pommes de terre (aloo masala)','Curry de papa (aloo masala)'),(420,'Bint as-sahn (pâtisserie yéménite à étages)','Bint as-sahn (pastel yemení en capas)'),
(421,'Poulet jerk jamaïcain','Pollo jerk jamaicano'),(422,'Pâtes crémeuses aux champignons','Pasta cremosa con champiñones'),(423,'Herrencreme (dessert allemand à la crème)','Herrencreme (postre alemán de crema)'),(424,'Pain aux bananes et au chocolat','Pan de plátano y chocolate'),(425,'Haricots noirs épicés','Frijoles negros picantes'),(426,'Risotto aux fruits de mer','Risotto de mariscos'),(427,'Riz frit au chou','Arroz frito con col'),(428,'Sauce babi panggang','Salsa babi panggang'),(429,'Soupe-repas bœuf et légumes','Sopa sustanciosa de res y verduras'),(430,'Poivre assaisonné','Pimienta sazonada'),
(431,'Brownies fondants','Brownies tipo fudge'),(432,'Chimichurri','Chimichurri'),(433,'Soupe pommes et panais','Sopa de manzana y chirivía'),(434,'Saumon croustillant','Salmón crujiente'),(435,'Gombo égyptien','Quimbombó egipcio'),(436,'Chili aux poivrons','Chili con pimientos'),(437,'Sauce tartare','Salsa tártara'),(438,'Sauce brune','Salsa gravy oscura'),(439,'Steak aux champignons','Bistec con champiñones'),(440,'Maïs soufflé','Palomitas de maíz'),
(441,'Cerises jubilé','Cerezas jubileo'),(442,'Salade de pommes de terre américaine I','Ensalada de papa estadounidense I'),(443,'Abula (trio de ragoûts nigérians)','Abula (tres guisos nigerianos)'),(444,'Salade de fruits au jus d’orange','Ensalada de frutas con jugo de naranja'),(445,'Biscuits aux pépites de chocolat III','Galletas con chispas de chocolate III'),(446,'Trempette au crabe','Dip de cangrejo'),(447,'Salade de germinations','Ensalada de germinados'),(448,'Côtes levées barbecue','Costillas a la barbacoa'),(449,'Soupe poivrée au poisson séché nigériane','Sopa picante nigeriana de pescado seco'),(450,'Sauce adobo','Salsa adobo'),
(451,'Chakchouka bil lahm (chakchouka libyenne à la viande)','Shakshuka bil lahm (shakshuka libia con carne)'),(452,'Pain à l’ail','Pan de ajo'),(453,'Riz frit épicé','Arroz frito picante'),(454,'Sheer khurma','Sheer khurma'),(455,'Nouilles aux œufs I','Fideos de huevo I'),(456,'Steak de bœuf poêlé','Bistec de res a la sartén'),(457,'Salsa piquante','Salsa picante'),(458,'Baingan bartha (aubergine à la noix de coco et au piment, Inde du Sud) I','Baingan bartha (berenjena con coco y chile, sur de la India) I'),(459,'Biscuits aux pépites de chocolat (sans gluten)','Galletas con chispas de chocolate (sin gluten)'),(460,'Aadun (farine de maïs à l’huile de palme)','Aadun (harina de maíz con aceite de palma)'),
(461,'Pyramides à la noix de coco','Pirámides de coco'),(462,'Poulet frit au chipotle','Pollo frito al chipotle'),(463,'Tamina (dessert algérien semoule et miel)','Tamina (postre argelino de sémola y miel)'),(464,'Salade de brocoli','Ensalada de brócoli'),(465,'Pain irlandais au bicarbonate (soda bread)','Pan irlandés de soda'),(466,'Aubergines à la parmesane (melanzane alla parmigiana) I','Berenjenas a la parmesana (melanzane alla parmigiana) I'),(467,'Poulet à la cannelle','Pollo a la canela'),(468,'Agedashi tofu','Agedashi tofu'),(469,'Tarte à la crème aux bananes I','Tarta de crema de plátano I'),(470,'Côtes levées de porc barbecue','Costillas de cerdo a la barbacoa'),
(471,'Beignet nigérian','Rosquilla nigeriana'),(472,'Steak pané frit (chicken-fried steak)','Bistec empanizado frito (chicken-fried steak)'),(473,'Salade d’épinards','Ensalada de espinacas'),(474,'Soupe au poulet et riz brun','Sopa de pollo con arroz integral'),(475,'Lait frappé aux Oreo','Batido de Oreo'),(476,'Banana split I','Banana split I'),(477,'Trempette au chipotle','Dip de chipotle'),(478,'Gâteau aux fruits','Pastel de frutas'),(479,'Tarte Tatin','Tarta Tatin'),(480,'Tarte chess','Tarta chess'),
(481,'Muffins citron et pavot glacés','Magdalenas glaseadas de limón y amapola'),(482,'Coleslaw I (salade de chou crémeuse)','Ensalada coleslaw I'),(483,'Yassa au poulet gambien','Yassa de pollo gambiano'),(484,'Croûtons à l’ail I','Crutones de ajo I'),(485,'Feijoada brésilienne','Feijoada brasileña'),(486,'Basboussa (gâteau égyptien à la semoule)','Basbusa (pastel egipcio de sémola)'),(487,'Crêpe de Henry Thiele','Panqueque de Henry Thiele'),(488,'Soda à l’orange','Refresco de naranja'),(489,'Kimchi au chou','Kimchi de col'),(490,'Crème cuite au four','Natillas horneadas'),
(491,'Gâteau au fromage de Vancouver','Tarta de queso de Vancouver'),(492,'Bouchées cacao-coco','Bocaditos de cacao y coco'),(493,'Casserole de tater tots','Cazuela de tater tots'),(494,'Gâteau au citron arrosé (lemon drizzle)','Bizcocho de limón glaseado (lemon drizzle)'),(495,'Vedhmi (galette sucrée farcie)','Vedhmi (pan plano dulce relleno)'),(496,'Riz frit barbecue','Arroz frito barbacoa'),(497,'Quatre-quarts au citron','Bizcocho de limón (pound cake)'),(498,'Riz frit au crabe','Arroz frito con cangrejo'),(499,'Baghrir algérien (crêpes mille trous)','Baghrir argelino (crepas de mil agujeros)'),(500,'Soupe aux pommes de terre et fromage','Sopa de papa con queso'),
(501,'Thé d’aubépine','Té de espino'),(502,'Muffins aux bananes et noix','Magdalenas de plátano y nueces'),(503,'Pouding au tapioca','Pudin de tapioca'),(504,'Sauce barbecue pour poulet','Salsa barbacoa para pollo'),(505,'Pad thaï','Pad thai'),(506,'Gâteau 1-2-3 au micro-ondes','Pastel 1-2-3 al microondas'),(507,'Ugali (bouillie de maïs rwandaise)','Ugali (gachas ruandesas de maíz)'),(508,'Sandwichs à la poitrine de bœuf barbecue','Sándwiches de pecho de res a la barbacoa'),(509,'Purée de châtaignes','Puré de castañas'),(510,'Vin d’abricot','Vino de albaricoque'),
(511,'Côtes levées barbecue à l’asiatique','Costillas a la barbacoa al estilo asiático'),(512,'Ailes de poulet barbecue','Alitas a la barbacoa'),(513,'Gâteau au citron et son glaçage','Pastel de limón con glaseado de limón'),(514,'Jambalaya I','Jambalaya I'),(515,'Soupe de côtes de porc (bak kut teh)','Sopa de costillas de cerdo (bak kut teh)'),(516,'Burgers de poulet croustillant','Hamburguesas de pollo crujiente'),(517,'Brioches à la cannelle','Rollos de canela'),(518,'Akamu (pouding nigérian)','Akamu (pudin nigeriano)'),(519,'Poulet Alfredo','Pollo Alfredo'),(520,'Soupe owo','Sopa owo'),
(521,'Pommes de terre au four','Papas al horno'),(522,'Mousse au café','Mousse de café'),(523,'Aubergines au four','Berenjena al horno'),(524,'Pommes de terre à la bengalie','Papas al estilo bengalí'),(525,'Confiture','Mermelada'),(526,'Ata ekuru (sauce pour ekuru)','Ata ekuru (salsa para ekuru)'),(527,'Galaktoboureko (feuilleté grec à la crème de semoule)','Galaktoboureko (pastel griego de crema de sémola)'),(528,'Tofu tandoori','Tofu tandoori'),(529,'Sandwich à la Vegemite','Sándwich de Vegemite'),(530,'Gâteau au chocolat au micro-ondes I','Pastel de chocolate al microondas I'),
(531,'Fèves au lard','Frijoles horneados'),(532,'Koki de maïs camerounais','Koki de maíz camerunés'),(533,'Riz frit au poulet','Arroz frito con pollo'),(534,'Cari de pommes de terre et chou-fleur (aloo gobi)','Curry de papa y coliflor (aloo gobi)'),(535,'Trempette aux palourdes','Dip de almejas'),(536,'Meringue aux noisettes','Merengue de avellanas'),(537,'Chili végane','Chili vegano'),(538,'Nouilles frites nigérianes','Fideos fritos nigerianos'),(539,'Banana split II','Banana split II'),(540,'Muffins au son','Magdalenas de salvado'),
(541,'Côtes levées de dos (baby back)','Costillas baby back'),(542,'Soupe aux Frittaten (lanières de crêpe)','Sopa de Frittaten (tiras de crepa)'),(543,'Po’boy','Po’boy'),(544,'Granité italien au citron','Granizado italiano de limón'),(545,'Soupe achi','Sopa achi'),(546,'Gâteau à café','Pastel para el café'),(547,'Gyoza au porc','Gyozas de cerdo'),(548,'Biscuits moelleux au gingembre','Galletas suaves de jengibre'),(549,'Farce à raviolis au fromage','Relleno de ravioles de queso'),(550,'Gallo pinto (riz et haricots costaricains)','Gallo pinto (arroz y frijoles costarricenses)'),
(551,'Bryndzové halušky (gnocchis slovaques au fromage de brebis)','Bryndzové halušky (ñoquis eslovacos con queso de oveja)'),(552,'Gratin de pommes de terre hongrois (rakott krumpli)','Cazuela húngara de papa (rakott krumpli)'),(553,'Steak de filet de bœuf','Filete de res'),(554,'Pouding à la noix de coco I','Pudin de coco I'),(555,'Bouchées jalapeño, saucisse et bacon (atomic buffalo turds)','Bocados de jalapeño, salchicha y tocino (atomic buffalo turds)'),(556,'Quartiers de pommes de terre panés','Gajos de papa empanizados'),(557,'Congee (gruau de riz chinois)','Congee (gachas chinas de arroz)'),(558,'Crème anglaise','Crema inglesa'),(559,'Caponata (aubergines et légumes à la sicilienne)','Caponata (berenjena y verduras a la siciliana)'),(560,'Écrevisses bouillies à la cajun','Hervido de cangrejos de río'),
(561,'Sauce acevichada','Salsa acevichada'),(562,'Soupe poireaux et pommes de terre','Sopa de puerro y papa'),(563,'Churros I','Churros I'),(564,'Frijoles antioqueños (ragoût de haricots colombien)','Frijoles antioqueños'),(565,'Tuwon dawa (pâte de sorgho nigériane)','Tuwon dawa (masa de sorgo nigeriana)'),(566,'Riz frit aux œufs nigérian','Arroz frito con huevo nigeriano'),(567,'Taboulé I','Tabulé I'),(568,'Springerle','Springerle'),(569,'Ashoka halwa (pouding aux haricots mungo)','Ashoka halwa (pudin de frijol mungo)'),(570,'Scones nature','Scones sencillos'),
(571,'Pain à la semoule','Pan de sémola'),(572,'Tarte banoffee','Tarta banoffee'),(573,'Bouillie de maïs et haricots nigériane','Gachas nigerianas de maíz y frijoles'),(574,'Poulet à la noix de coco','Pollo al coco'),(575,'Ragoût d’aubergines africaines (garden egg)','Guiso de berenjena africana (garden egg)'),(576,'Crêpes aux amandes','Panqueques de almendra'),(577,'Saumon grillé sur planche','Salmón a la plancha de madera'),(578,'Galettes de crabe','Pastelitos de cangrejo'),(579,'Feijoada portugaise','Feijoada portuguesa'),(580,'Pétoncles enrobés de bacon','Vieiras envueltas en tocino'),
(581,'Paella d’inspiration valencienne','Paella de inspiración valenciana'),(582,'Penne au four','Penne al horno'),(583,'Baklava aux pistaches','Baklava de pistacho'),(584,'Biscuits citrouille et pépites de chocolat','Galletas de calabaza con chispas de chocolate'),(585,'Meringues aux pépites de chocolat','Merenguitos con chispas de chocolate'),(586,'Cari bangladais','Curry bangladesí'),(587,'Brownies gâteau','Brownies tipo pastel'),(588,'Saumon grillé à l’asiatique','Salmón a la parrilla al estilo asiático'),(589,'Asperges à l’ail','Espárragos al ajo'),(590,'Maïs en crème','Maíz cremoso'),
(591,'Crème de papaye','Crema de papaya'),(592,'Rôties sésame-crevettes','Tostadas de camarón con sésamo'),(593,'Tarte au mincemeat','Tarta de mincemeat'),(594,'Glaçage à la cassonade','Glaseado de azúcar moreno'),(595,'Hamburger deluxe','Hamburguesa deluxe'),(596,'Feuilles de vigne farcies égyptiennes (warak enab mahshi)','Hojas de parra rellenas egipcias (warak enab mahshi)'),(597,'Bœuf sauté','Salteado de res'),(598,'Jahnun (pâtisserie yéménite roulée)','Jahnun (masa yemení enrollada)'),(599,'Burger cajun','Hamburguesa cajún'),(600,'Pâtes aux aubergines','Pasta con berenjena'),
(601,'Cannoli','Cannoli'),(602,'Biscuits de Shrewsbury','Galletas de Shrewsbury'),(603,'Mousse aux fruits','Espuma de frutas'),(604,'Lasagne aux épinards et à la ricotta','Lasaña de espinaca y ricota'),(605,'Irish potatoes (bonbons à la noix de coco et cannelle)','Irish potatoes (dulces de coco y canela)'),(606,'Tacos','Tacos'),(607,'Mille-feuille au citron','Milhojas de limón'),(608,'Papa turmada (gratin de pommes de terre et saucisse)','Papa turmada (cazuela de papa y salchicha)'),(609,'Boulettes de viande à l’italienne','Albóndigas italianas'),(610,'Casserole aux œufs','Cazuela de huevo'),
(611,'Soupe egusi','Sopa egusi'),(612,'Vinaigrette italienne II','Aderezo italiano II'),(613,'Pommes au bourbon','Manzanas al bourbon'),(614,'Haricots frits nigérians','Frijoles fritos nigerianos'),(615,'Pakoras aux oignons','Pakoras de cebolla'),(616,'Croquettes de bœuf','Croquetas de res'),(617,'Brocoli sauté','Brócoli salteado'),(618,'Tourte aux légumes albanaise','Pastel albanés de verduras'),(619,'Crème au citron (lemon curd)','Crema de limón (lemon curd)'),(620,'Salade de poulet d’inspiration asiatique','Ensalada de pollo de inspiración asiática'),
(621,'Sauce Alfredo','Salsa Alfredo'),(622,'Saucisses et purée (bangers and mash)','Salchichas con puré (bangers and mash)'),(623,'Beurre blanc','Salsa beurre blanc'),(624,'Crêpes véganes','Panqueques veganos'),(625,'Soda à l’œuf vietnamien','Soda con huevo vietnamita'),(626,'Bacon fumé au bois de pommier','Tocino ahumado con madera de manzano'),(627,'Haggis','Haggis'),(628,'Beignets aux pommes','Buñuelos de manzana'),(629,'Gaufres déjeuner','Gofres de desayuno'),(630,'Tarte aux pommes II','Tarta de manzana II'),
(631,'Anticuchos (brochettes de cœur de bœuf)','Anticuchos (brochetas de corazón de res)'),(632,'Tempe mendoan I','Tempe mendoan I'),(633,'Arroz negro (riz valencien à l’encre de seiche)','Arroz negro (arroz valenciano con tinta de calamar)'),(634,'Sauce au poulet libérienne','Salsa de pollo liberiana')
),
base as (
  select r.id, row_number() over (order by r.id) n
  from public.recipes r
  where r.status='published'
    and not exists (select 1 from public.recipe_title_translations x where x.recipe_id=r.id and x.language_code='fr')
)
insert into public.recipe_title_translations (recipe_id, language_code, title, model)
select b.id, l.code, case l.code when 'fr' then t.fr else t.es end, 'claude-titres-2026-10-05'
from t join base b using (n)
cross join (values ('fr'), ('es')) l(code)
on conflict do nothing;
end $migration$;
