
do $$
declare
  v_author uuid := 'ac515660-4852-4ebd-8cb5-3348d60e06e9';
  v_recipe uuid;
  v_place uuid;
begin
  v_recipe := '10000000-0000-4000-8000-000000000001';
  select id into v_place from public.culinary_places where slug='it-naples';
  insert into public.recipes (id,author_id,title,slug,description,excerpt,source_language,country_code,region,category,authenticity,status,difficulty,prep_minutes,cook_minutes,servings,published_at,primary_place_id,is_editorial,source_name,source_url,source_notes)
  values (v_recipe,v_author,'Pizza Margherita napolitaine','pizza-margherita-napolitaine','Une version maison fidèle à l’esprit de la pizza Margherita de Naples : pâte souple, tomate, mozzarella, basilic et huile d’olive.','Tomate, mozzarella, basilic et pâte à pizza cuite très chaud.','fr','IT','Naples','Pizza','adapted','published','medium',30,8,2,now(),v_place,true,'Italia.it','https://www.italia.it/en/campania/naples/things-to-do/pizza','Version éditoriale adaptée. L’association à Naples et les éléments caractéristiques de la Margherita sont documentés par Italia.it; les proportions et instructions sont rédigées pour cette application.')
  on conflict (id) do update set title=excluded.title,slug=excluded.slug,description=excluded.description,excerpt=excluded.excerpt,country_code=excluded.country_code,region=excluded.region,category=excluded.category,authenticity=excluded.authenticity,status=excluded.status,difficulty=excluded.difficulty,prep_minutes=excluded.prep_minutes,cook_minutes=excluded.cook_minutes,servings=excluded.servings,published_at=excluded.published_at,primary_place_id=excluded.primary_place_id,is_editorial=excluded.is_editorial,source_name=excluded.source_name,source_url=excluded.source_url,source_notes=excluded.source_notes;
  delete from public.recipe_ingredients where recipe_id=v_recipe;
  insert into public.recipe_ingredients(recipe_id,position,name,quantity,unit,note) values
    (v_recipe,0,'Farine type 00 ou farine à pain',250,'g',null),(v_recipe,1,'Eau à température ambiante',160,'ml',null),(v_recipe,2,'Sel fin',7,'g',null),(v_recipe,3,'Levure sèche instantanée',0.8,'g','environ 1/4 c. à thé'),(v_recipe,4,'Tomates pelées de bonne qualité',120,'g','écrasées à la main'),(v_recipe,5,'Mozzarella fraîche',100,'g','bien égouttée'),(v_recipe,6,'Huile d’olive extra vierge',10,'ml',null),(v_recipe,7,'Feuilles de basilic frais',6,'unité',null);
  delete from public.recipe_steps where recipe_id=v_recipe;
  insert into public.recipe_steps(recipe_id,position,instruction,timer_seconds) values
    (v_recipe,0,'Mélanger l’eau et la levure. Ajouter la farine puis le sel et pétrir jusqu’à obtenir une pâte lisse et souple.',null),(v_recipe,1,'Couvrir et laisser lever jusqu’à ce que la pâte soit bien détendue et gonflée. Pour plus de goût, laisser fermenter plusieurs heures au frais.',null),(v_recipe,2,'Préchauffer le four avec une pierre ou une plaque épaisse à la température maximale pendant au moins 30 minutes.',1800),(v_recipe,3,'Former deux boules. Étirer une boule à la main en gardant un rebord légèrement plus épais.',null),(v_recipe,4,'Étendre une fine couche de tomate, répartir la mozzarella égouttée et arroser légèrement d’huile d’olive.',null),(v_recipe,5,'Cuire à chaleur maximale jusqu’à ce que le dessous soit cuit et le rebord bien coloré. Ajouter le basilic frais à la sortie du four.',null);
  delete from public.recipe_locations where recipe_id=v_recipe;
  insert into public.recipe_locations(recipe_id,place_id,relation,is_primary) values(v_recipe,v_place,'origin',true);
  delete from public.recipe_images where recipe_id=v_recipe and source_type='external_licensed';
  insert into public.recipe_images(recipe_id,source_type,status,external_url,alt_text,source_name,source_page_url,photographer_name,photographer_url,license_name,license_url,attribution_text,is_primary,is_representative)
  values(v_recipe,'external_licensed','ready','https://upload.wikimedia.org/wikipedia/commons/f/f4/PizzaMargherita.jpg','Pizza Margherita','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:PizzaMargherita.jpg','SIG SG 510','https://commons.wikimedia.org/wiki/User:SIG_SG_510','CC0 1.0','https://creativecommons.org/publicdomain/zero/1.0/','Photo : SIG SG 510 · Wikimedia Commons · CC0 1.0',true,true);
  delete from public.place_specialties where place_id=v_place and name='Pizza Margherita';
  insert into public.place_specialties(place_id,recipe_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  values(v_place,v_recipe,'Pizza Margherita','Pizza napolitaine garnie de tomate, mozzarella et basilic.','Naples',true,1,'Italia.it','https://www.italia.it/en/campania/naples/things-to-do/pizza');

  v_recipe := '10000000-0000-4000-8000-000000000002';
  select id into v_place from public.culinary_places where slug='id-bali';
  insert into public.recipes (id,author_id,title,slug,description,excerpt,source_language,country_code,region,category,authenticity,status,difficulty,prep_minutes,cook_minutes,servings,published_at,primary_place_id,is_editorial,source_name,source_url,source_notes)
  values (v_recipe,v_author,'Ayam Betutu balinais','ayam-betutu-balinais','Poulet balinais longuement cuit avec une pâte d’épices aromatique inspirée du bumbu betutu.','Poulet épicé de Bali, cuit lentement jusqu’à devenir très tendre.','fr','ID','Bali','Poulet','adapted','published','medium',35,150,6,now(),v_place,true,'Indonesia Travel','https://www.indonesia.travel/in/en/travel-ideas/gastronomy/ayam-betutu-balis-iconic-spiced-chicken-dish','Version éditoriale adaptée. Indonesia Travel documente le poulet entier, le mélange d’épices balinais et la cuisson lente/à la vapeur; les quantités sont propres à cette application.')
  on conflict (id) do update set title=excluded.title,slug=excluded.slug,description=excluded.description,excerpt=excluded.excerpt,country_code=excluded.country_code,region=excluded.region,category=excluded.category,authenticity=excluded.authenticity,status=excluded.status,difficulty=excluded.difficulty,prep_minutes=excluded.prep_minutes,cook_minutes=excluded.cook_minutes,servings=excluded.servings,published_at=excluded.published_at,primary_place_id=excluded.primary_place_id,is_editorial=excluded.is_editorial,source_name=excluded.source_name,source_url=excluded.source_url,source_notes=excluded.source_notes;
  delete from public.recipe_ingredients where recipe_id=v_recipe;
  insert into public.recipe_ingredients(recipe_id,position,name,quantity,unit,note) values
    (v_recipe,0,'Poulet entier',1.5,'kg',null),(v_recipe,1,'Échalotes',8,'unité','grossièrement hachées'),(v_recipe,2,'Gousses d’ail',6,'unité',null),(v_recipe,3,'Piments rouges',3,'unité','ajuster au goût'),(v_recipe,4,'Curcuma frais ou moulu',2,'c. à thé',null),(v_recipe,5,'Gingembre frais',25,'g',null),(v_recipe,6,'Galanga frais',25,'g','ou gingembre supplémentaire'),(v_recipe,7,'Citronnelle',2,'tige','partie tendre'),(v_recipe,8,'Graines de coriandre moulues',2,'c. à thé',null),(v_recipe,9,'Noix de bancoul ou noix de macadamia',4,'unité','option pratique'),(v_recipe,10,'Feuilles de combava',4,'unité',null),(v_recipe,11,'Sel',2,'c. à thé',null),(v_recipe,12,'Huile neutre',2,'c. à soupe',null),(v_recipe,13,'Feuilles de bananier',2,'grande','facultatif, pour envelopper');
  delete from public.recipe_steps where recipe_id=v_recipe;
  insert into public.recipe_steps(recipe_id,position,instruction,timer_seconds) values
    (v_recipe,0,'Mixer ou piler les échalotes, l’ail, les piments, le curcuma, le gingembre, le galanga, la citronnelle, la coriandre, les noix, le sel et l’huile pour former une pâte épaisse.',null),(v_recipe,1,'Enduire le poulet à l’intérieur et à l’extérieur avec la pâte d’épices. Glisser les feuilles de combava dans la cavité.',null),(v_recipe,2,'Envelopper serré dans les feuilles de bananier, puis dans du papier cuisson ou du papier d’aluminium si nécessaire.',null),(v_recipe,3,'Cuire doucement au four à 160 °C pendant environ 2 heures, jusqu’à ce que la viande soit très tendre.',7200),(v_recipe,4,'Ouvrir l’enveloppe et augmenter le four à 220 °C pendant 15 à 20 minutes pour colorer légèrement la peau.',1000),(v_recipe,5,'Servir avec du riz vapeur et, si désiré, un sambal frais.',null);
  delete from public.recipe_locations where recipe_id=v_recipe;
  insert into public.recipe_locations(recipe_id,place_id,relation,is_primary) values(v_recipe,v_place,'origin',true);
  delete from public.recipe_images where recipe_id=v_recipe and source_type='external_licensed';
  insert into public.recipe_images(recipe_id,source_type,status,external_url,alt_text,source_name,source_page_url,photographer_name,photographer_url,license_name,license_url,attribution_text,is_primary,is_representative)
  values(v_recipe,'external_licensed','ready','https://upload.wikimedia.org/wikipedia/commons/7/70/Ayam_betutu.jpg','Ayam betutu servi à Bali','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Ayam_betutu.jpg','Muhammad Hanif Nasution','https://commons.wikimedia.org/wiki/User:Muhammad_Hanif_Nasution','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Photo : Muhammad Hanif Nasution · Wikimedia Commons · CC BY-SA 4.0',true,true);
  delete from public.place_specialties where place_id=v_place and name='Ayam Betutu';
  insert into public.place_specialties(place_id,recipe_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  values(v_place,v_recipe,'Ayam Betutu','Poulet balinais aux épices, traditionnellement cuit lentement.','Bali',true,1,'Indonesia Travel','https://www.indonesia.travel/in/en/travel-ideas/gastronomy/ayam-betutu-balis-iconic-spiced-chicken-dish');

  v_recipe := '10000000-0000-4000-8000-000000000003';
  select id into v_place from public.culinary_places where slug='mx-oaxaca-city';
  insert into public.recipes (id,author_id,title,slug,description,excerpt,source_language,country_code,region,category,authenticity,status,difficulty,prep_minutes,cook_minutes,servings,published_at,primary_place_id,is_editorial,source_name,source_url,source_notes)
  values (v_recipe,v_author,'Tlayuda oaxaqueña','tlayuda-oaxaquena','Grande tortilla oaxaqueña grillée, garnie de haricots, quesillo, légumes et viande au choix.','Une grande tortilla croustillante garnie à la manière des marchés d’Oaxaca.','fr','MX','Oaxaca de Juárez','Cuisine de rue','adapted','published','easy',20,15,2,now(),v_place,true,'Visit Mexico','https://visitmexico.com/en/destino/18469/esmercado-hidalgoenhidalgo-market','Version éditoriale adaptée. Visit Mexico documente les tlayudas parmi les antojitos traditionnels servis à Oaxaca; les quantités et la méthode sont rédigées pour cette application.')
  on conflict (id) do update set title=excluded.title,slug=excluded.slug,description=excluded.description,excerpt=excluded.excerpt,country_code=excluded.country_code,region=excluded.region,category=excluded.category,authenticity=excluded.authenticity,status=excluded.status,difficulty=excluded.difficulty,prep_minutes=excluded.prep_minutes,cook_minutes=excluded.cook_minutes,servings=excluded.servings,published_at=excluded.published_at,primary_place_id=excluded.primary_place_id,is_editorial=excluded.is_editorial,source_name=excluded.source_name,source_url=excluded.source_url,source_notes=excluded.source_notes;
  delete from public.recipe_ingredients where recipe_id=v_recipe;
  insert into public.recipe_ingredients(recipe_id,position,name,quantity,unit,note) values
    (v_recipe,0,'Grande tortilla pour tlayuda',1,'unité','ou grande tortilla de maïs très ferme'),(v_recipe,1,'Haricots noirs cuits',180,'g','écrasés'),(v_recipe,2,'Saindoux ou huile neutre',1,'c. à soupe','le asiento est traditionnel lorsqu’il est disponible'),(v_recipe,3,'Quesillo d’Oaxaca',120,'g','effiloché; mozzarella faible humidité en dépannage'),(v_recipe,4,'Tasajo, carne asada ou chorizo',180,'g','grillé et tranché'),(v_recipe,5,'Chou ou laitue finement émincé',1,'tasse',null),(v_recipe,6,'Tomate',1,'unité','tranchée'),(v_recipe,7,'Avocat',1,'unité','tranché'),(v_recipe,8,'Salsa rouge ou verte',4,'c. à soupe',null);
  delete from public.recipe_steps where recipe_id=v_recipe;
  insert into public.recipe_steps(recipe_id,position,instruction,timer_seconds) values
    (v_recipe,0,'Griller la viande choisie jusqu’à cuisson complète, puis la garder au chaud.',null),(v_recipe,1,'Réchauffer les haricots écrasés avec le saindoux ou l’huile jusqu’à obtenir une texture tartinable.',null),(v_recipe,2,'Faire chauffer la grande tortilla sur une plaque ou un gril jusqu’à ce qu’elle devienne chaude, légèrement sèche et croustillante par endroits.',null),(v_recipe,3,'Étendre les haricots sur la tortilla, puis ajouter le quesillo et laisser fondre légèrement.',null),(v_recipe,4,'Ajouter la viande, le chou, la tomate et l’avocat.',null),(v_recipe,5,'Terminer avec la salsa. Servir ouverte ou pliée en deux selon la préférence.',null);
  delete from public.recipe_locations where recipe_id=v_recipe;
  insert into public.recipe_locations(recipe_id,place_id,relation,is_primary) values(v_recipe,v_place,'origin',true);
  delete from public.recipe_images where recipe_id=v_recipe and source_type='external_licensed';
  insert into public.recipe_images(recipe_id,source_type,status,external_url,alt_text,source_name,source_page_url,photographer_name,photographer_url,license_name,license_url,attribution_text,is_primary,is_representative)
  values(v_recipe,'external_licensed','ready','https://upload.wikimedia.org/wikipedia/commons/b/bd/Tlayuda.jpg','Tlayuda oaxaqueña','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Tlayuda.jpg','German matus','https://commons.wikimedia.org/wiki/User:German_matus','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Photo : German matus · Wikimedia Commons · CC BY-SA 4.0',true,true);
  delete from public.place_specialties where place_id=v_place and name='Tlayuda';
  insert into public.place_specialties(place_id,recipe_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  values(v_place,v_recipe,'Tlayuda','Grande tortilla de maïs garnie, emblématique des antojitos oaxaqueños.','Oaxaca de Juárez',true,1,'Visit Mexico','https://visitmexico.com/en/destino/18469/esmercado-hidalgoenhidalgo-market');
  insert into public.place_specialties(place_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  select v_place,'Mole','Sauces complexes à base de piments, épices et autres ingrédients; nombreuses variantes à Oaxaca.','Oaxaca',false,2,'Visit Mexico','https://visitmexico.com/en/destino/18469/esmercado-hidalgoenhidalgo-market'
  where not exists(select 1 from public.place_specialties where place_id=v_place and name='Mole');
  insert into public.place_specialties(place_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  select v_place,'Memela','Masa de maïs épaisse garnie, vendue dans les marchés et comedores d’Oaxaca.','Oaxaca de Juárez',false,3,'Visit Mexico','https://visitmexico.com/en/destino/18469/esmercado-hidalgoenhidalgo-market'
  where not exists(select 1 from public.place_specialties where place_id=v_place and name='Memela');

  v_recipe := '10000000-0000-4000-8000-000000000004';
  select id into v_place from public.culinary_places where slug='th-chiang-mai-city';
  insert into public.recipes (id,author_id,title,slug,description,excerpt,source_language,country_code,region,category,authenticity,status,difficulty,prep_minutes,cook_minutes,servings,published_at,primary_place_id,is_editorial,source_name,source_url,source_notes)
  values (v_recipe,v_author,'Khao Soi de Chiang Mai','khao-soi-chiang-mai','Soupe de nouilles au curry du nord de la Thaïlande, riche en lait de coco, garnie de nouilles croustillantes, échalotes, légumes marinés et lime.','Nouilles au curry et lait de coco, spécialité emblématique de Chiang Mai.','fr','TH','Chiang Mai','Soupe de nouilles','adapted','published','medium',25,45,4,now(),v_place,true,'Tourism Authority of Thailand','https://api-tourismproduct.tourismthailand.org/uploads/2025/10/ebook/All_Eng_Green_Tourism_compress/file/10c2f106-3262-4f29-9477-2be9a055ae0e.pdf','Version éditoriale adaptée. Tourism Authority of Thailand qualifie le khao soi de plat signature de Chiang Mai et documente bouillon au curry, lait de coco, viande, échalotes, légumes marinés et lime.')
  on conflict (id) do update set title=excluded.title,slug=excluded.slug,description=excluded.description,excerpt=excluded.excerpt,country_code=excluded.country_code,region=excluded.region,category=excluded.category,authenticity=excluded.authenticity,status=excluded.status,difficulty=excluded.difficulty,prep_minutes=excluded.prep_minutes,cook_minutes=excluded.cook_minutes,servings=excluded.servings,published_at=excluded.published_at,primary_place_id=excluded.primary_place_id,is_editorial=excluded.is_editorial,source_name=excluded.source_name,source_url=excluded.source_url,source_notes=excluded.source_notes;
  delete from public.recipe_ingredients where recipe_id=v_recipe;
  insert into public.recipe_ingredients(recipe_id,position,name,quantity,unit,note) values
    (v_recipe,0,'Cuisses de poulet désossées',500,'g','coupées en morceaux'),(v_recipe,1,'Nouilles aux œufs fraîches',400,'g',null),(v_recipe,2,'Lait de coco',400,'ml',null),(v_recipe,3,'Bouillon de poulet',500,'ml',null),(v_recipe,4,'Pâte de curry rouge',3,'c. à soupe',null),(v_recipe,5,'Curcuma moulu',1,'c. à thé',null),(v_recipe,6,'Poudre de curry',1,'c. à thé',null),(v_recipe,7,'Sauce de poisson',2,'c. à soupe',null),(v_recipe,8,'Sucre de palme ou cassonade',1,'c. à soupe',null),(v_recipe,9,'Échalotes',2,'unité','émincées'),(v_recipe,10,'Légumes moutardés marinés',100,'g','hachés'),(v_recipe,11,'Lime',2,'unité','en quartiers'),(v_recipe,12,'Huile',250,'ml','pour frire une petite portion de nouilles'),(v_recipe,13,'Coriandre fraîche',0.5,'tasse','facultatif');
  delete from public.recipe_steps where recipe_id=v_recipe;
  insert into public.recipe_steps(recipe_id,position,instruction,timer_seconds) values
    (v_recipe,0,'Réserver environ 80 g de nouilles crues pour la garniture croustillante. Cuire le reste selon l’emballage, égoutter et répartir dans quatre bols.',null),(v_recipe,1,'Chauffer un peu de crème épaisse prélevée du dessus du lait de coco. Faire revenir la pâte de curry, le curcuma et la poudre de curry jusqu’à ce qu’ils deviennent très parfumés.',null),(v_recipe,2,'Ajouter le poulet, puis le reste du lait de coco et le bouillon. Laisser mijoter doucement jusqu’à ce que le poulet soit tendre.',1800),(v_recipe,3,'Assaisonner avec la sauce de poisson et le sucre. Ajuster pour obtenir un équilibre salé, légèrement sucré et épicé.',null),(v_recipe,4,'Frire rapidement les nouilles réservées dans l’huile chaude jusqu’à ce qu’elles soient dorées et croustillantes. Égoutter.',null),(v_recipe,5,'Verser le curry chaud sur les nouilles cuites. Garnir de nouilles frites, échalotes, légumes marinés, coriandre et quartiers de lime.',null);
  delete from public.recipe_locations where recipe_id=v_recipe;
  insert into public.recipe_locations(recipe_id,place_id,relation,is_primary) values(v_recipe,v_place,'origin',true);
  delete from public.recipe_images where recipe_id=v_recipe and source_type='external_licensed';
  insert into public.recipe_images(recipe_id,source_type,status,external_url,alt_text,source_name,source_page_url,photographer_name,photographer_url,license_name,license_url,attribution_text,is_primary,is_representative)
  values(v_recipe,'external_licensed','ready','https://upload.wikimedia.org/wikipedia/commons/d/d9/Khao_Soi.jpg','Bol de khao soi illustratif','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Khao_Soi.jpg','Pequeño mar','https://commons.wikimedia.org/wiki/User:Peque%C3%B1o_mar','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0/','Photo illustrative : Pequeño mar · Wikimedia Commons · CC BY-SA 4.0',true,true);
  delete from public.place_specialties where place_id=v_place and name='Khao Soi';
  insert into public.place_specialties(place_id,recipe_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  values(v_place,v_recipe,'Khao Soi','Nouilles au curry et lait de coco avec garnitures fraîches et croustillantes.','Chiang Mai',true,1,'Tourism Authority of Thailand','https://api-tourismproduct.tourismthailand.org/uploads/2025/10/ebook/All_Eng_Green_Tourism_compress/file/10c2f106-3262-4f29-9477-2be9a055ae0e.pdf');

  v_recipe := '10000000-0000-4000-8000-000000000005';
  select id into v_place from public.culinary_places where slug='jp-sapporo';
  insert into public.recipes (id,author_id,title,slug,description,excerpt,source_language,country_code,region,category,authenticity,status,difficulty,prep_minutes,cook_minutes,servings,published_at,primary_place_id,is_editorial,source_name,source_url,source_notes)
  values (v_recipe,v_author,'Ramen miso style Sapporo','ramen-miso-style-sapporo','Bol de ramen inspiré de Sapporo avec bouillon au miso, nouilles, porc, germes de soja, maïs et une touche de beurre.','Ramen au miso inspiré de Sapporo, avec maïs, beurre et légumes.','fr','JP','Sapporo','Ramen','adapted','published','medium',20,35,4,now(),v_place,true,'Japan National Tourism Organization','https://www.japan.travel/en/destinations/hokkaido/hokkaido/sapporo-and-around/','Version éditoriale adaptée. JNTO identifie Sapporo au ramen miso; les proportions et la méthode sont une version maison originale.')
  on conflict (id) do update set title=excluded.title,slug=excluded.slug,description=excluded.description,excerpt=excluded.excerpt,country_code=excluded.country_code,region=excluded.region,category=excluded.category,authenticity=excluded.authenticity,status=excluded.status,difficulty=excluded.difficulty,prep_minutes=excluded.prep_minutes,cook_minutes=excluded.cook_minutes,servings=excluded.servings,published_at=excluded.published_at,primary_place_id=excluded.primary_place_id,is_editorial=excluded.is_editorial,source_name=excluded.source_name,source_url=excluded.source_url,source_notes=excluded.source_notes;
  delete from public.recipe_ingredients where recipe_id=v_recipe;
  insert into public.recipe_ingredients(recipe_id,position,name,quantity,unit,note) values
    (v_recipe,0,'Nouilles ramen',4,'portion',null),(v_recipe,1,'Bouillon de poulet non salé',1.2,'L',null),(v_recipe,2,'Miso rouge ou awase',100,'g',null),(v_recipe,3,'Porc haché ou porc rôti tranché',300,'g',null),(v_recipe,4,'Germes de soja',250,'g',null),(v_recipe,5,'Maïs en grains',200,'g',null),(v_recipe,6,'Ail',3,'gousse','hachées'),(v_recipe,7,'Gingembre frais',20,'g','râpé'),(v_recipe,8,'Huile de sésame',1,'c. à soupe',null),(v_recipe,9,'Sauce soja',1,'c. à soupe',null),(v_recipe,10,'Oignons verts',4,'unité','émincés'),(v_recipe,11,'Beurre',40,'g','10 g par bol'),(v_recipe,12,'Graines de sésame',1,'c. à soupe','facultatif');
  delete from public.recipe_steps where recipe_id=v_recipe;
  insert into public.recipe_steps(recipe_id,position,instruction,timer_seconds) values
    (v_recipe,0,'Chauffer l’huile de sésame dans une casserole. Faire revenir le porc, l’ail et le gingembre jusqu’à ce que le porc soit cuit et légèrement coloré.',null),(v_recipe,1,'Ajouter le bouillon et laisser mijoter environ 15 minutes.',900),(v_recipe,2,'Prélever une louche de bouillon chaud et y dissoudre le miso. Remettre dans la casserole sans faire bouillir vigoureusement. Ajouter la sauce soja.',null),(v_recipe,3,'Sauter rapidement les germes de soja dans une poêle chaude afin qu’ils restent légèrement croquants.',null),(v_recipe,4,'Cuire les nouilles ramen séparément selon leur temps de cuisson puis bien les égoutter.',null),(v_recipe,5,'Répartir les nouilles dans les bols. Ajouter le bouillon au miso, le porc, les germes de soja, le maïs et les oignons verts.',null),(v_recipe,6,'Déposer une petite noix de beurre sur chaque bol juste avant de servir.',null);
  delete from public.recipe_locations where recipe_id=v_recipe;
  insert into public.recipe_locations(recipe_id,place_id,relation,is_primary) values(v_recipe,v_place,'origin',true);
  delete from public.recipe_images where recipe_id=v_recipe and source_type='external_licensed';
  insert into public.recipe_images(recipe_id,source_type,status,external_url,alt_text,source_name,source_page_url,photographer_name,photographer_url,license_name,license_url,attribution_text,is_primary,is_representative)
  values(v_recipe,'external_licensed','ready','https://upload.wikimedia.org/wikipedia/commons/2/25/Sapporo_miso_ramen.jpg','Ramen miso photographié à Sapporo','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Sapporo_miso_ramen.jpg','Schellack','https://en.wikipedia.org/wiki/User:Schellack','CC BY 3.0','https://creativecommons.org/licenses/by/3.0/','Photo : Schellack · Wikimedia Commons · CC BY 3.0',true,true);
  delete from public.place_specialties where place_id=v_place and name='Ramen miso';
  insert into public.place_specialties(place_id,recipe_id,name,description,origin_note,is_signature,sort_order,source_name,source_url)
  values(v_place,v_recipe,'Ramen miso','Ramen au bouillon miso, spécialité fortement associée à Sapporo.','Sapporo',true,1,'Japan National Tourism Organization','https://www.japan.travel/en/destinations/hokkaido/hokkaido/sapporo-and-around/');
end $$;

notify pgrst, 'reload schema';