-- Photos Wikimedia Commons vérifiées une à une (le fichier représente ce plat), auteur et licence conservés.
-- Sixième passe, suite (noms locaux dans les titres de fichiers Commons) : 6 photos de plus.
-- N'ajoute une photo qu'aux recettes publiées qui n'en ont pas encore : relancer ne duplique rien.
insert into public.recipe_images (recipe_id, source_type, status, external_url, alt_text, source_name, source_page_url,
  photographer_name, license_name, license_url, attribution_text, is_primary, is_representative, moderation_notes)
select r.id, 'external_licensed', 'ready', e->>'url', r.title, 'Wikimedia Commons', e->>'page',
  nullif(e->>'author', ''), e->>'license', nullif(e->>'licenseUrl', ''),
  'Photo : ' || coalesce(nullif(e->>'author', ''), 'auteur inconnu') || ' · ' || (e->>'license') || ' · Wikimedia Commons',
  true, true, 'Photo Wikimedia Commons vérifiée : le fichier représente ce plat.'
from jsonb_array_elements($photos$[{"slug":"shurbo-tadjik","file":"File:Shurbo - Tadschikische Küche.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/7/74/Shurbo_-_Tadschikische_K%C3%BCche.jpg","page":"https://commons.wikimedia.org/wiki/File:Shurbo_-_Tadschikische_K%C3%BCche.jpg","author":"Schokifaktor","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0"},{"slug":"matoke-ougandais","file":"File:Matoke, 2010.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/5/5d/Matoke%2C_2010.jpg","page":"https://commons.wikimedia.org/wiki/File:Matoke,_2010.jpg","author":"Michele Zanin","license":"CC BY-SA 2.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/2.0"},{"slug":"eru-camerounais","file":"File:Eru Soup.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/5/5f/Eru_Soup.jpg","page":"https://commons.wikimedia.org/wiki/File:Eru_Soup.jpg","author":"Aderiqueza","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0"},{"slug":"chamucas-mocambicanas","file":"File:Chamuças en Afrique portugaise.JPG","url":"https://upload.wikimedia.org/wikipedia/commons/e/ed/Chamu%C3%A7as_en_Afrique_portugaise.JPG","page":"https://commons.wikimedia.org/wiki/File:Chamu%C3%A7as_en_Afrique_portugaise.JPG","author":"Marianne Casamance","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0"},{"slug":"morogo-botswana","file":"File:Morogo wa Thepe.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/f/f8/Morogo_wa_Thepe.jpg","page":"https://commons.wikimedia.org/wiki/File:Morogo_wa_Thepe.jpg","author":"JupiterKB","license":"CC0","licenseUrl":"http://creativecommons.org/publicdomain/zero/1.0/deed.en"},{"slug":"appa-sri-lankais","file":"File:Egg Hopper - The Coconut Island 2025-10-05.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/f/f1/Egg_Hopper_-_The_Coconut_Island_2025-10-05.jpg","page":"https://commons.wikimedia.org/wiki/File:Egg_Hopper_-_The_Coconut_Island_2025-10-05.jpg","author":"Andy Li","license":"CC0","licenseUrl":"http://creativecommons.org/publicdomain/zero/1.0/deed.en"}]$photos$::jsonb) as e
join public.recipes r on (e ? 'id' and r.id = (e->>'id')::uuid) or (e ? 'slug' and r.slug = e->>'slug')
where r.status = 'published'
  and not exists (select 1 from public.recipe_images i where i.recipe_id = r.id and i.status = 'ready');
