-- Photos Wikimedia Commons vérifiées une à une (le fichier représente ce plat), auteur et licence conservés.
-- Sixième passe (recherche Commons ciblée, à la main) : 8 photos sur les 147 recettes restantes.
-- N'ajoute une photo qu'aux recettes publiées qui n'en ont pas encore : relancer ne duplique rien.
insert into public.recipe_images (recipe_id, source_type, status, external_url, alt_text, source_name, source_page_url,
  photographer_name, license_name, license_url, attribution_text, is_primary, is_representative, moderation_notes)
select r.id, 'external_licensed', 'ready', e->>'url', r.title, 'Wikimedia Commons', e->>'page',
  nullif(e->>'author', ''), e->>'license', nullif(e->>'licenseUrl', ''),
  'Photo : ' || coalesce(nullif(e->>'author', ''), 'auteur inconnu') || ' · ' || (e->>'license') || ' · Wikimedia Commons',
  true, true, 'Photo Wikimedia Commons vérifiée : le fichier représente ce plat.'
from jsonb_array_elements($photos$[{"id":"5121c1b8-8f88-43ae-9be9-cdf15405f9c7","file":"File:Roasted Garlic Redskin Potatoes.JPG","url":"https://upload.wikimedia.org/wikipedia/commons/6/69/Roasted_Garlic_Redskin_Potatoes.JPG","page":"https://commons.wikimedia.org/wiki/File:Roasted_Garlic_Redskin_Potatoes.JPG","author":"Robert Loescher","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0"},{"id":"a4d5f2e9-a8fb-42aa-b3ee-e2c3ce7ee381","file":"File:Sweet Potato Fries.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/4/46/Sweet_Potato_Fries.jpg","page":"https://commons.wikimedia.org/wiki/File:Sweet_Potato_Fries.jpg","author":"Sanjay Acharya","license":"CC BY-SA 3.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/3.0"},{"id":"200127ae-88b4-493f-8dbb-e22c12ec1125","file":"File:Caramel Sauce - Caramel Syrup.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/7/7f/Caramel_Sauce_-_Caramel_Syrup.jpg","page":"https://commons.wikimedia.org/wiki/File:Caramel_Sauce_-_Caramel_Syrup.jpg","author":"Rebecca Siegel","license":"CC BY 2.0","licenseUrl":"https://creativecommons.org/licenses/by/2.0"},{"id":"d629d08a-b568-4aad-93e5-a791a1cb9bef","file":"File:Bringebærsyltetøy Feb 2015.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/8/8b/Bringeb%C3%A6rsyltet%C3%B8y_Feb_2015.jpg","page":"https://commons.wikimedia.org/wiki/File:Bringeb%C3%A6rsyltet%C3%B8y_Feb_2015.jpg","author":"Kjetil Ree","license":"CC BY-SA 3.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/3.0"},{"id":"6a66be2e-3287-40c4-af5f-da9a78305956","file":"File:Kazakh quwyrdaq.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/c/c6/Kazakh_quwyrdaq.jpg","page":"https://commons.wikimedia.org/wiki/File:Kazakh_quwyrdaq.jpg","author":"Rio Murr from Minsk, Belarus","license":"CC BY-SA 2.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/2.0"},{"slug":"karjalanpaisti","file":"File:Karelskastek1.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/2/2a/Karelskastek1.jpg","page":"https://commons.wikimedia.org/wiki/File:Karelskastek1.jpg","author":"Sari Moo","license":"Public domain","licenseUrl":null},{"slug":"conkies-barbade","file":"File:Conkie.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/0/0a/Conkie.jpg","page":"https://commons.wikimedia.org/wiki/File:Conkie.jpg","author":"Foodista","license":"CC BY 2.0","licenseUrl":"https://creativecommons.org/licenses/by/2.0"},{"slug":"rougaille-saucisses-maurice","file":"File:Rougail Saucisse 04-07-07.jpg","url":"https://upload.wikimedia.org/wikipedia/commons/c/cb/Rougail_Saucisse_04-07-07.jpg","page":"https://commons.wikimedia.org/wiki/File:Rougail_Saucisse_04-07-07.jpg","author":"flo77220","license":"CC BY-SA 3.0","licenseUrl":"http://creativecommons.org/licenses/by-sa/3.0/"}]$photos$::jsonb) as e
join public.recipes r on (e ? 'id' and r.id = (e->>'id')::uuid) or (e ? 'slug' and r.slug = e->>'slug')
where r.status = 'published'
  and not exists (select 1 from public.recipe_images i where i.recipe_id = r.id and i.status = 'ready');
