create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create extension if not exists pg_trgm with schema extensions;

create type public.recipe_status as enum ('draft', 'published', 'archived');
create type public.recipe_difficulty as enum ('easy', 'medium', 'hard');
create type public.recipe_authenticity as enum ('traditional', 'adapted', 'fusion');
create type public.measurement_system as enum ('metric', 'imperial', 'cups');
create type public.temperature_unit as enum ('c', 'f');
create type public.notification_type as enum ('comment', 'rating', 'like', 'follow', 'cook_attempt', 'system');
create type public.report_reason as enum ('spam', 'abuse', 'copyright', 'unsafe', 'misinformation', 'other');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text,
  avatar_path text,
  country_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (username is null or char_length(username) between 3 and 32)
);

create table public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  language_code text not null default 'fr',
  country_code text not null default 'CA',
  measurement_system public.measurement_system not null default 'metric',
  temperature_unit public.temperature_unit not null default 'c',
  currency_code text not null default 'CAD',
  translate_recipes boolean not null default true,
  translate_comments boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint user_preferences_language_length check (char_length(language_code) between 2 and 10),
  constraint user_preferences_country_length check (char_length(country_code) between 2 and 3),
  constraint user_preferences_currency_length check (char_length(currency_code) between 3 and 3)
);

create table public.recipes (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  source_language text not null default 'en',
  country_code text,
  region text,
  category text,
  authenticity public.recipe_authenticity not null default 'adapted',
  status public.recipe_status not null default 'draft',
  difficulty public.recipe_difficulty,
  prep_minutes integer,
  cook_minutes integer,
  servings numeric(8,2),
  cover_image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint recipes_title_length check (char_length(title) between 2 and 180),
  constraint recipes_description_length check (description is null or char_length(description) <= 5000),
  constraint recipes_prep_nonnegative check (prep_minutes is null or prep_minutes >= 0),
  constraint recipes_cook_nonnegative check (cook_minutes is null or cook_minutes >= 0),
  constraint recipes_servings_positive check (servings is null or servings > 0)
);

create table public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  position integer not null default 0,
  name text not null,
  quantity numeric(12,4),
  unit text,
  note text,
  created_at timestamptz not null default now(),
  constraint recipe_ingredients_quantity_nonnegative check (quantity is null or quantity >= 0)
);

create table public.recipe_steps (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  position integer not null,
  instruction text not null,
  timer_seconds integer,
  image_path text,
  created_at timestamptz not null default now(),
  constraint recipe_steps_position_nonnegative check (position >= 0),
  constraint recipe_steps_timer_nonnegative check (timer_seconds is null or timer_seconds >= 0)
);

create table public.recipe_ratings (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null,
  review text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (recipe_id, user_id),
  constraint recipe_ratings_range check (rating between 1 and 5),
  constraint recipe_ratings_review_length check (review is null or char_length(review) <= 3000)
);

create table public.recipe_comments (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  parent_comment_id uuid references public.recipe_comments(id) on delete cascade,
  body text not null,
  language_code text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint recipe_comments_body_length check (char_length(body) between 1 and 4000)
);

create table public.recipe_likes (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recipe_id, user_id)
);

create table public.favorites (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recipe_id, user_id)
);

create table public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint follows_no_self check (follower_id <> following_id)
);

create table public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint blocks_no_self check (blocker_id <> blocked_id)
);

create table public.cook_attempts (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  note text,
  image_path text,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  constraint cook_attempts_note_length check (note is null or char_length(note) <= 3000)
);

create table public.content_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  recipe_id uuid references public.recipes(id) on delete cascade,
  comment_id uuid references public.recipe_comments(id) on delete cascade,
  reported_user_id uuid references auth.users(id) on delete cascade,
  reason public.report_reason not null,
  details text,
  created_at timestamptz not null default now(),
  constraint content_reports_one_target check (
    ((recipe_id is not null)::int + (comment_id is not null)::int + (reported_user_id is not null)::int) = 1
  ),
  constraint content_reports_details_length check (details is null or char_length(details) <= 3000)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  type public.notification_type not null,
  recipe_id uuid references public.recipes(id) on delete cascade,
  comment_id uuid references public.recipe_comments(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.recipe_translations (
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  language_code text not null,
  title text not null,
  description text,
  ingredients jsonb not null default '[]'::jsonb,
  steps jsonb not null default '[]'::jsonb,
  translated_at timestamptz not null default now(),
  model text,
  primary key (recipe_id, language_code)
);

create table public.comment_translations (
  comment_id uuid not null references public.recipe_comments(id) on delete cascade,
  language_code text not null,
  body text not null,
  translated_at timestamptz not null default now(),
  model text,
  primary key (comment_id, language_code)
);

create table public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature text not null,
  provider text not null default 'openai',
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  credits_used integer not null default 1,
  estimated_cost_cad_micros bigint not null default 0,
  created_at timestamptz not null default now(),
  constraint ai_usage_tokens_nonnegative check (input_tokens >= 0 and output_tokens >= 0),
  constraint ai_usage_credits_positive check (credits_used > 0),
  constraint ai_usage_cost_nonnegative check (estimated_cost_cad_micros >= 0)
);

create table public.entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'free',
  ai_monthly_credits integer not null default 10,
  ai_credits_used integer not null default 0,
  period_start timestamptz not null default date_trunc('month', now()),
  period_end timestamptz not null default (date_trunc('month', now()) + interval '1 month'),
  updated_at timestamptz not null default now(),
  constraint entitlements_credits_nonnegative check (ai_monthly_credits >= 0 and ai_credits_used >= 0)
);

create table public.billing_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

create index recipes_author_id_idx on public.recipes(author_id);
create index recipes_status_published_idx on public.recipes(status, published_at desc);
create index recipes_country_category_idx on public.recipes(country_code, category);
create index recipes_title_trgm_idx on public.recipes using gin (title gin_trgm_ops);
create index recipes_description_trgm_idx on public.recipes using gin (description gin_trgm_ops);
create index recipe_ingredients_recipe_id_idx on public.recipe_ingredients(recipe_id, position);
create index recipe_ingredients_name_trgm_idx on public.recipe_ingredients using gin (name gin_trgm_ops);
create index recipe_steps_recipe_id_idx on public.recipe_steps(recipe_id, position);
create index recipe_ratings_recipe_id_idx on public.recipe_ratings(recipe_id);
create index recipe_comments_recipe_id_created_idx on public.recipe_comments(recipe_id, created_at desc);
create index recipe_comments_user_id_idx on public.recipe_comments(user_id);
create index recipe_likes_recipe_id_idx on public.recipe_likes(recipe_id);
create index favorites_user_id_idx on public.favorites(user_id, created_at desc);
create index follows_following_id_idx on public.follows(following_id);
create index cook_attempts_recipe_id_idx on public.cook_attempts(recipe_id, created_at desc);
create index content_reports_reporter_idx on public.content_reports(reporter_id, created_at desc);
create index notifications_user_unread_idx on public.notifications(user_id, read_at, created_at desc);
create index ai_usage_events_user_created_idx on public.ai_usage_events(user_id, created_at desc);

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function private.set_updated_at();
create trigger user_preferences_set_updated_at before update on public.user_preferences
for each row execute function private.set_updated_at();
create trigger recipes_set_updated_at before update on public.recipes
for each row execute function private.set_updated_at();
create trigger recipe_ratings_set_updated_at before update on public.recipe_ratings
for each row execute function private.set_updated_at();
create trigger recipe_comments_set_updated_at before update on public.recipe_comments
for each row execute function private.set_updated_at();
create trigger entitlements_set_updated_at before update on public.entitlements
for each row execute function private.set_updated_at();
create trigger billing_accounts_set_updated_at before update on public.billing_accounts
for each row execute function private.set_updated_at();

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_path, country_code)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name'),
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'country_code'
  )
  on conflict (id) do nothing;

  insert into public.user_preferences (user_id, language_code, country_code, currency_code)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'language_code', 'fr'),
    coalesce(new.raw_user_meta_data->>'country_code', 'CA'),
    coalesce(new.raw_user_meta_data->>'currency_code', 'CAD')
  )
  on conflict (user_id) do nothing;

  insert into public.entitlements (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.recipe_steps enable row level security;
alter table public.recipe_ratings enable row level security;
alter table public.recipe_comments enable row level security;
alter table public.recipe_likes enable row level security;
alter table public.favorites enable row level security;
alter table public.follows enable row level security;
alter table public.user_blocks enable row level security;
alter table public.cook_attempts enable row level security;
alter table public.content_reports enable row level security;
alter table public.notifications enable row level security;
alter table public.recipe_translations enable row level security;
alter table public.comment_translations enable row level security;
alter table public.ai_usage_events enable row level security;
alter table public.entitlements enable row level security;
alter table public.billing_accounts enable row level security;

create policy profiles_public_read on public.profiles
for select to anon, authenticated using (true);
create policy profiles_owner_insert on public.profiles
for insert to authenticated with check ((select auth.uid()) = id);
create policy profiles_owner_update on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy preferences_owner_read on public.user_preferences
for select to authenticated using ((select auth.uid()) = user_id);
create policy preferences_owner_insert on public.user_preferences
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy preferences_owner_update on public.user_preferences
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy recipes_read_published_or_owner on public.recipes
for select to anon, authenticated
using (status = 'published' or (select auth.uid()) = author_id);
create policy recipes_owner_insert on public.recipes
for insert to authenticated with check ((select auth.uid()) = author_id);
create policy recipes_owner_update on public.recipes
for update to authenticated
using ((select auth.uid()) = author_id)
with check ((select auth.uid()) = author_id);
create policy recipes_owner_delete on public.recipes
for delete to authenticated using ((select auth.uid()) = author_id);

create policy ingredients_read_visible_recipe on public.recipe_ingredients
for select to anon, authenticated using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_id
      and (r.status = 'published' or r.author_id = (select auth.uid()))
  )
);
create policy ingredients_owner_insert on public.recipe_ingredients
for insert to authenticated with check (
  exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid()))
);
create policy ingredients_owner_update on public.recipe_ingredients
for update to authenticated
using (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())))
with check (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())));
create policy ingredients_owner_delete on public.recipe_ingredients
for delete to authenticated
using (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())));

create policy steps_read_visible_recipe on public.recipe_steps
for select to anon, authenticated using (
  exists (
    select 1 from public.recipes r
    where r.id = recipe_id
      and (r.status = 'published' or r.author_id = (select auth.uid()))
  )
);
create policy steps_owner_insert on public.recipe_steps
for insert to authenticated with check (
  exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid()))
);
create policy steps_owner_update on public.recipe_steps
for update to authenticated
using (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())))
with check (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())));
create policy steps_owner_delete on public.recipe_steps
for delete to authenticated
using (exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid())));

create policy ratings_read_published on public.recipe_ratings
for select to anon, authenticated using (
  exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy ratings_owner_insert on public.recipe_ratings
for insert to authenticated with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy ratings_owner_update on public.recipe_ratings
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy ratings_owner_delete on public.recipe_ratings
for delete to authenticated using ((select auth.uid()) = user_id);

create policy comments_read_visible on public.recipe_comments
for select to anon, authenticated using (
  ((deleted_at is null) and exists (
    select 1 from public.recipes r where r.id = recipe_id and r.status = 'published'
  ))
  or user_id = (select auth.uid())
);
create policy comments_owner_insert on public.recipe_comments
for insert to authenticated with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy comments_owner_update on public.recipe_comments
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy comments_owner_delete on public.recipe_comments
for delete to authenticated using ((select auth.uid()) = user_id);

create policy likes_read_published on public.recipe_likes
for select to anon, authenticated using (
  exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy likes_owner_insert on public.recipe_likes
for insert to authenticated with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy likes_owner_delete on public.recipe_likes
for delete to authenticated using ((select auth.uid()) = user_id);

create policy favorites_owner_read on public.favorites
for select to authenticated using ((select auth.uid()) = user_id);
create policy favorites_owner_insert on public.favorites
for insert to authenticated with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy favorites_owner_delete on public.favorites
for delete to authenticated using ((select auth.uid()) = user_id);

create policy follows_public_read on public.follows
for select to anon, authenticated using (true);
create policy follows_owner_insert on public.follows
for insert to authenticated with check ((select auth.uid()) = follower_id);
create policy follows_owner_delete on public.follows
for delete to authenticated using ((select auth.uid()) = follower_id);

create policy blocks_owner_read on public.user_blocks
for select to authenticated using ((select auth.uid()) = blocker_id);
create policy blocks_owner_insert on public.user_blocks
for insert to authenticated with check ((select auth.uid()) = blocker_id);
create policy blocks_owner_delete on public.user_blocks
for delete to authenticated using ((select auth.uid()) = blocker_id);

create policy attempts_read_visible on public.cook_attempts
for select to anon, authenticated using (
  (visible and exists (
    select 1 from public.recipes r where r.id = recipe_id and r.status = 'published'
  ))
  or user_id = (select auth.uid())
);
create policy attempts_owner_insert on public.cook_attempts
for insert to authenticated with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
);
create policy attempts_owner_update on public.cook_attempts
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy attempts_owner_delete on public.cook_attempts
for delete to authenticated using ((select auth.uid()) = user_id);

create policy reports_owner_read on public.content_reports
for select to authenticated using ((select auth.uid()) = reporter_id);
create policy reports_owner_insert on public.content_reports
for insert to authenticated with check ((select auth.uid()) = reporter_id);

create policy notifications_owner_read on public.notifications
for select to authenticated using ((select auth.uid()) = user_id);
create policy notifications_owner_update on public.notifications
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy notifications_owner_delete on public.notifications
for delete to authenticated using ((select auth.uid()) = user_id);

create policy recipe_translations_public_read on public.recipe_translations
for select to anon, authenticated using (
  exists (select 1 from public.recipes r where r.id = recipe_id and r.status = 'published')
  or exists (select 1 from public.recipes r where r.id = recipe_id and r.author_id = (select auth.uid()))
);
create policy comment_translations_public_read on public.comment_translations
for select to anon, authenticated using (
  exists (
    select 1
    from public.recipe_comments c
    join public.recipes r on r.id = c.recipe_id
    where c.id = comment_id
      and c.deleted_at is null
      and r.status = 'published'
  )
  or exists (
    select 1 from public.recipe_comments c
    where c.id = comment_id and c.user_id = (select auth.uid())
  )
);

create policy ai_usage_owner_read on public.ai_usage_events
for select to authenticated using ((select auth.uid()) = user_id);

create policy entitlements_owner_read on public.entitlements
for select to authenticated using ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;

grant select on public.profiles, public.recipes, public.recipe_ingredients, public.recipe_steps,
  public.recipe_ratings, public.recipe_comments, public.recipe_likes, public.follows,
  public.cook_attempts, public.recipe_translations, public.comment_translations
to anon, authenticated;

grant select on public.user_preferences, public.favorites, public.user_blocks, public.content_reports,
  public.notifications, public.ai_usage_events, public.entitlements
to authenticated;

grant insert, update on public.profiles, public.user_preferences, public.recipes,
  public.recipe_ingredients, public.recipe_steps, public.recipe_ratings, public.recipe_comments,
  public.cook_attempts
to authenticated;

grant insert on public.recipe_likes, public.favorites, public.follows, public.user_blocks,
  public.content_reports
to authenticated;

grant update on public.notifications to authenticated;

grant delete on public.recipes, public.recipe_ingredients, public.recipe_steps, public.recipe_ratings,
  public.recipe_comments, public.recipe_likes, public.favorites, public.follows, public.user_blocks,
  public.cook_attempts, public.notifications
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 5242880, array['image/jpeg','image/png','image/webp','image/avif']),
  ('recipe-images', 'recipe-images', true, 10485760, array['image/jpeg','image/png','image/webp','image/avif']),
  ('cook-images', 'cook-images', true, 10485760, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy storage_public_read_app_images on storage.objects
for select to anon, authenticated
using (bucket_id in ('avatars', 'recipe-images', 'cook-images'));

create policy storage_user_upload_app_images on storage.objects
for insert to authenticated
with check (
  bucket_id in ('avatars', 'recipe-images', 'cook-images')
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy storage_user_update_app_images on storage.objects
for update to authenticated
using (
  bucket_id in ('avatars', 'recipe-images', 'cook-images')
  and owner_id = (select auth.uid())::text
)
with check (
  bucket_id in ('avatars', 'recipe-images', 'cook-images')
  and owner_id = (select auth.uid())::text
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy storage_user_delete_app_images on storage.objects
for delete to authenticated
using (
  bucket_id in ('avatars', 'recipe-images', 'cook-images')
  and owner_id = (select auth.uid())::text
);
